title: "Tom's Recipes"
description: >
  Recipes from various sources stored in markdown
url: "https://recipes.nyxtom.dev"
author: &default_author
  name: Tom Holloway
twitter:
  username: nyxtom
license_url: https://creativecommons.org/licenses/by-nc/4.0/
feedback_url: https://github.com/nyxtom/recipes/issues/new
repository_url: https://github.com/nyxtom/recipes
remote_theme: nyxtom/jekyll-theme-scribbles

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
      author: *default_author

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

sass:
  style: compressed
